name: links
version: '2.15'
summary: Web browser running in text mode
description: |
  Links is a text mode WWW browser, similar to Lynx. It displays tables,
  frames, downloads on background, uses HTTP/1.1 keepalive connections.

grade: stable
confinement: strict

apps:
  links:
    command: links
    plugs:
      - home
      - network
      - network-bind

parts:
  links:
    plugin: make
    source: http://links.twibright.com/download/links-${SNAPCRAFT_PROJECT_VERSION}.tar.bz2
    build-packages:
      - gcc
      - libssl-dev
    override-build: |
      ./configure --with-ssl --without-fb --without-x --enable-javascript
      make
      cp links $SNAPCRAFT_PART_INSTALL
